name: Frontend Workflow

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main]
    workflow_dispatch: # adds a manual "Run workflow" button to your GitHub repository webpage
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # 1. Set up Node.js on the GitHub runner 
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-size: "16"
                  cache: "npm"
                  cache-dependency-path: ./frontend/package-lock.json

            # 2. Install dependencies on the GitHub runner 
            - name: Install Frontend dependencies
              run: |
                  cd frontend
                  npm ci

            # 3. Run Frontend tests on the GitHub runner 
            - name: Run Frontend tests
              run: |
                  cd frontend
                  npm run test

            # 4. Run Frontend linting on the GitHub runner
            - name: Run Frontend linting
              run: |
                  cd frontend
                  npm run lint

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN}}

            - name: Build and push Frontend image
              uses: docker/build-push-action@v4
              with:
                  context: ./frontend
                  push: true
                  tags: |
                      ${{ secrets.DOCKER_USERNAME }}/frontend-vacation:latest
                      ${{ secrets.DOCKER_USERNAME }}/frontend-vacation:${{ github.sha }}
